#!/bin/bash

# Script para testar todos os métodos CRUD de cronogramas
# Este script cria um arquivo de testes e documenta os testes disponíveis

echo "=========================================="
echo "TESTES CRUD DE CRONOGRAMAS"
echo "=========================================="
echo ""
echo "Nota: Certifique-se de que MySQL está rodando antes de executar este script."
echo ""
echo "PASSOS PARA EXECUTAR OS TESTES:"
echo ""
echo "1. Verificar que MySQL está rodando:"
echo "   sudo service mysql start"
echo ""
echo "2. Executar migrations com seeders:"
echo "   php artisan migrate:fresh --seed"
echo ""
echo "3. Executar testes de Feature (Web CRUD):"
echo "   php artisan test tests/Feature/CronogramaTest.php"
echo ""
echo "4. Executar testes de API:"
echo "   php artisan test tests/Feature/CronogramaApiTest.php"
echo ""
echo "5. Executar todos os testes de Cronogramas:"
echo "   php artisan test tests/Feature/CronogramaTest.php tests/Feature/CronogramaApiTest.php"
echo ""
echo "6. Executar testes com output detalhado:"
echo "   php artisan test tests/Feature/CronogramaTest.php --verbose"
echo ""
echo "=========================================="
echo "RESUMO DOS TESTES CRIADOS:"
echo "=========================================="
echo ""
echo "📋 TESTES WEB (CronogramaTest.php) - 30 testes"
echo "   CREATE:"
echo "     ✓ test_store_cronograma_com_dados_validos"
echo "     ✓ test_store_cronograma_curso_inexistente"
echo "     ✓ test_store_cronograma_periodo_invalido"
echo "     ✓ test_store_cronograma_hora_fora_do_periodo_manha"
echo "     ✓ test_store_cronograma_hora_formato_invalido"
echo "     ✓ test_store_cronograma_periodo_tarde"
echo "     ✓ test_store_cronograma_periodo_noite"
echo ""
echo "   READ:"
echo "     ✓ test_index_lista_todos_cronogramas"
echo "     ✓ test_index_carrega_dados_curso"
echo "     ✓ test_show_cronograma_individual"
echo "     ✓ test_show_cronograma_inexistente"
echo "     ✓ test_create_exibe_formulario"
echo ""
echo "   UPDATE:"
echo "     ✓ test_update_cronograma_com_dados_validos"
echo "     ✓ test_update_cronograma_inexistente"
echo "     ✓ test_update_cronograma_muda_periodo"
echo "     ✓ test_edit_exibe_formulario"
echo ""
echo "   DELETE:"
echo "     ✓ test_destroy_cronograma"
echo "     ✓ test_destroy_cronograma_inexistente"
echo "     ✓ test_destroy_multiplos_cronogramas"
echo ""
echo "   RELATIONSHIPS & VALIDATION:"
echo "     ✓ test_cronograma_carrega_curso"
echo "     ✓ test_index_cronogramas_com_curso_carregado"
echo "     ✓ test_validacao_campos_obrigatorios"
echo "     ✓ test_validacao_dia_semana"
echo ""
echo "📡 TESTES API (CronogramaApiTest.php) - 28 testes"
echo "   POST (CREATE):"
echo "     ✓ test_api_store_cronograma_valido"
echo "     ✓ test_api_store_curso_inexistente"
echo "     ✓ test_api_store_hora_fim_anterior_inicio"
echo "     ✓ test_api_store_conflito_horario"
echo "     ✓ test_api_store_dia_semana_invalido"
echo "     ✓ test_api_store_todos_dias_semana"
echo ""
echo "   GET (READ):"
echo "     ✓ test_api_index_lista_cronogramas"
echo "     ✓ test_api_index_carrega_curso"
echo "     ✓ test_api_show_cronograma"
echo "     ✓ test_api_show_cronograma_inexistente"
echo "     ✓ test_api_show_carrega_curso"
echo ""
echo "   PUT (UPDATE):"
echo "     ✓ test_api_update_cronograma"
echo "     ✓ test_api_update_curso_id_ignorado"
echo "     ✓ test_api_update_cronograma_inexistente"
echo "     ✓ test_api_update_validar_horas"
echo ""
echo "   DELETE:"
echo "     ✓ test_api_destroy_cronograma"
echo "     ✓ test_api_destroy_cronograma_inexistente"
echo "     ✓ test_api_destroy_multiplos_cronogramas"
echo ""
echo "   BATCH & INTEGRATION:"
echo "     ✓ test_batch_create_cronogramas"
echo "     ✓ test_ciclo_completo_crud"
echo ""
echo "📊 SEEDER INFORMATION:"
echo "   CronogramaSeeder.php - Seeds 17 cronogramas com:"
echo "     • Múltiplos períodos (manhã, tarde, noite)"
echo "     • Todos os dias da semana"
echo "     • Múltiplos cronogramas por curso"
echo "     • Horas válidas para cada período"
echo ""
echo "📦 FACTORY INFORMATION:"
echo "   CronogramaFactory.php criado com métodos:"
echo "     • manha() - gera cronograma para período da manhã"
echo "     • tarde() - gera cronograma para período da tarde"
echo "     • noite() - gera cronograma para período da noite"
echo "     • forCurso(Curso) - vincula a um curso específico"
echo "     • forDia(string) - define um dia específico"
echo ""
echo "=========================================="
echo "TOTAL: 58 testes de CRUD criados"
echo "=========================================="
